/// Flutter icons FirstTaskBasicIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  FirstTaskBasicIcons
///      fonts:
///       - asset: fonts/FirstTaskBasicIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class FirstTaskBasicIcons {
  FirstTaskBasicIcons._();

  static const _kFontFam = 'FirstTaskBasicIcons';
  static const String? _kFontPkg = null;

  static const IconData border_outer = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData border_top = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_down = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData geo_alt = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData three_dots = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tools = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData upload = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
